### ISSUE TITLE
dimension error in your exampleCase

### ISSUE THREAD

**Issue by sssaabb** [zuozqi/comPhaseChangeInterFoam#3]
Thanks for sharing your code. 

I success to compile your code in my openfoam(v2106)

Then, I tried to run your exampleCase/pressuriztionLN2tank

But, The openfoam made a fatal error.

[0] --> FOAM FATAL ERROR: 
[0] Different dimensions for '(a - b)'
     dimensions : [1 -1 -2 0 0 0 0] != [1 -3 -2 0 0 0 0]
[0] 
[0] 
[0]     From function bool Foam::checkDims(const char*, const Foam::dimensionSet&, const Foam::dimensionSet&)
[0]     in file dimensionSet/dimensionSet.C at line 56.
[0] 
FOAM parallel run aborting

If you are okay, Could you give me some advice?

Thanks.

**Comment by mjson1** [comment]
> Thanks for sharing your code.
> 
> I success to compile your code in my openfoam(v2106)
> 
> Then, I tried to run your exampleCase/pressuriztionLN2tank
> 
> But, The openfoam made a fatal error.
> 
> [0] --> FOAM FATAL ERROR: [0] Different dimensions for '(a - b)' dimensions : [1 -1 -2 0 0 0 0] != [1 -3 -2 0 0 0 0] [0] [0] [0] From function bool Foam::checkDims(const char*, const Foam::dimensionSet&, const Foam::dimensionSet&) [0] in file dimensionSet/dimensionSet.C at line 56. [0] FOAM parallel run aborting
> 
> If you are okay, Could you give me some advice?
> 
> Thanks.

**Comment by JatoOF** [comment]
@sssaabb hi, have you fixed out the inconsistency of dimensions?
